### ISSUE TITLE
v1.1.3 postinstall requires rush to be installed

### ISSUE THREAD

**Issue by MSNev** [microsoft/DynamicProto-JS#36]
With the postinstall, this is causing the installing of the package to fail

**Comment by MSNev** [comment]
Waiting for official build -- should be about 15-30 mins before it finishes and we can publish the updated version (1.1.4) which fixes this

**Comment by MSNev** [comment]
v1.1.4 is now released with the fix

**Comment by bawse** [comment]
This is still an issue when proto-js is a peer dependency. My project has the following applicationinsights-web dependency:

"@microsoft/applicationinsights-web": "^2.3.1",

Failing on npm install.

**Comment by MSNev** [comment]
And if you update your lock file to use 1.1.4 instead of 1.1.3?

**Comment by MSNev** [comment]
I've also just unpublished v1.1.3 to avoid this issue completely, which will of course now give failures about an unknown version -- but basically you need to use v1.1.4

**Comment by MSNev** [comment]
Closing now as 1.1.4 has been published and tagging 1.1.3 as deprecated should be informative (hopefully).
Working on some ideas for updating the testing infra so this sort of thing doesn't happen again for all of our repo's not just this one.
