### ISSUE TITLE
Exclude files from published package

### ISSUE THREAD

**Issue by mjbvz** [microsoft/DynamicProto-JS#61]
Hi, I noticed that npm package for this library includes files that seem like they should not be published:

- `microsoft-dynamicproto-js-1.1.7.tgz` — a zip of the project itself?
- `lib/test` — Tests?
- `list/docs` — Documentation?
- Top level documentation files such  as `CODE_OF_CONDUCT.md`, `SUPPORT.md`

Removing these will cut the on-disk size of the install by more than 50%

**Comment by MSNev** [comment]
Removing the tests makes sense. To remove the docs will needs to change so that we publish them somewhere so they are directly usable. Most likely won't get to this until 2023.

**Comment by mjbvz** [comment]
Thanks

Just curious, has application insights considered moving of this package? `#private` properties seem to solve most (if not all) of the problems listed in the readme and are also more well understood by modern bundlers

**Comment by MSNev** [comment]
The issue is that v2 needs to support ES3 (IE8) and this is not just dealing with private properties.
The primary goal is to avoid the `Class.prototype.`funcname generated code (for ES3 and ES5) targets

**Comment by mjbvz** [comment]
What about for v3? 

Just some background: I'm on the VS Code team and application insights is currently a rather sizable part of our extension bundle size. Exploring reducing that lead me to file this issue (although this issue will not have an impact on the bundle size but will be a nice improvement for npm install size)

**Comment by MSNev** [comment]
For v3 we are lifting the min-bar to ES5 (IE9+), so only slightly more "modern"...

**Comment by MSNev** [comment]
Based on internal build generation, we have also removed the based src and the docs are now published to https://microsoft.github.io/DynamicProto-JS/typedoc/index.html

**Comment by MSNev** [comment]
v1.1.8 is still including a bunch of stuff that it shouldn't -- including the real expected package *.tgz file.
This was caused by a mis-configuration of our internal npm publish task -- fixing
