### ISSUE TITLE
Bump external library Sinon.JS to newer version which does not use eval

### ISSUE THREAD

**Issue by egloff** [microsoft/DynamicProto-JS#65]
As described in ticket https://github.com/Azure/azure-sdk-for-js/issues/24903 the current version of the external library Sinon.JS (1.17.2 from 2015) uses `eval` for some purpose and therefore all projects that use _Microsoft Dynamic Proto Utility_ or libraries depending on it (like _@azure/communication-calling_) are required to allow `script-src: unsafe-eval` in the CSP policy.

Would it be possible to use at least version 2.0.0 (from 2017), which does not use `eval` anymore? (Ticket: https://github.com/sinonjs/sinon/issues/710, Releasenotes: https://github.com/sinonjs/sinon/releases/tag/v2.0.0)

**Comment by MSNev** [comment]
WIll look at it, however, why is your usage of DynamicProto dragging in local testing components??

is it perhaps related to #61 -- because we have (accidently) included the test framework?
-- This would be an easier and quicker fix.

**Comment by MSNev** [comment]
Looks like we are already using 2.3.8 and the 1.17.2 included in the repo is no longer used
